SejaHeroi/Controllers/LoginController.cs
using SejaHeroi.Enums;
using SejaHeroi.Extensions;
using SejaHeroi.Models;
using System.Linq;
using System.Web.Mvc;

namespace SejaHeroi.Controllers
{
    public class LoginController : BaseController
    {
        // POST: Login/Autenticar
        [AllowAnonymous]
        [HttpPost]
        public ActionResult Autenticar(Usuario usuario)
        {
            var user = (from userlist in _SejaHeroiContext.Usuarios
                        where userlist.Login == usuario.Login && userlist.Senha == usuario.Senha
                        select new
                        {
                            userlist.UsuarioID,
                            userlist.Login,
                            userlist.PerfilUsuario,
                        }).ToList();
            var usuarioEncontrado = user.FirstOrDefault();
            if (usuarioEncontrado != null)
            {
                this.AddNotification($"Bem vindo Herói!", NotificationType.INFO);
                Session["Perfil"] = usuarioEncontrado.PerfilUsuario;
                Session["UsuarioID"] = usuarioEncontrado.UsuarioID;
                    return Redirect("/Home/index");
            }
            else
            {
                this.AddNotification("Login/senha Inválido", NotificationType.ERROR); 
            }
            return View("Index");
        }

        public override ActionResult Index()
        {
            Session["Perfil"] = PerfilUsuario.Adotante;
            Session["UsuarioID"] = "";
            return base.Index();
        }

    }
}

SejaHeroi/Controllers/UsuarioController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using SejaHeroi.Models;

namespace SejaHeroi.Controllers
{
    public class UsuarioController : BaseController
    {  
        // GET: Usuarios
        public override ActionResult Index()
        {
            
            return View(_SejaHeroiContext.Usuarios.ToList());
        }

        // GET: Usuarios/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = _SejaHeroiContext.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // GET: Usuarios/Create
        public ActionResult Create()
        {
            ViewBag.Perfil = TempData["Perfil"];
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UsuarioID,PerfilUsuario,Login,Senha,Email")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                usuario.UsuarioID = Guid.NewGuid();
                _SejaHeroiContext.Usuarios.Add(usuario);
                _SejaHeroiContext.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = _SejaHeroiContext.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UsuarioID,PerfilUsuario,Login,Senha,Email")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                _SejaHeroiContext.Entry(usuario).State = EntityState.Modified;
                _SejaHeroiContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = _SejaHeroiContext.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Usuario usuario = _SejaHeroiContext.Usuarios.Find(id);
            _SejaHeroiContext.Usuarios.Remove(usuario);
            _SejaHeroiContext.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _SejaHeroiContext.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SejaHeroi/Views/Login/index.cshtml
@model SejaHeroi.Models.Usuario

@{
    ViewBag.Title = "index";
}

<!doctype html>
<html lang="pt">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="css/estilo.css" media="screen" />

    <!-- Bootstrap CSS -->
    @*<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">*@
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <title>Seja um Herói</title>
    <style>
        * {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }

        body {
            background: rgb(219, 226, 226);
        }

        .row {
            background: white;
            border-radius: 30px;
            box-shadow: 12px 12px 12px grey;
        }

        img {
            border-top-left-radius: 30px;
            border-bottom-left-radius: 30px;
        }

        .btn1 {
            border: none;
            outline: none;
            height: 50px;
            width: 100%;
            background-color: rgb(51, 153, 255);
            color: white;
            border-radius: 4px;
            font-weight: bold;
        }

            .btn1:hover {
                background: white;
                border: 1px solid;
                color: rgb(51, 153, 255);
            }

        .btn2 {
            border: none;
            outline: none;
            height: 50px;
            width: 100%;
            background-color: rgb(255, 0, 0);
            color: white;
            border-radius: 4px;
            font-weight: bold;
        }

            .btn2:hover {
                background: white;
                border: 1px solid;
                color: rgb(255, 0, 0);
            }
    </style>
</head>
<body>

    @using (Html.BeginForm("Autenticar", "Login", FormMethod.Post))
    { 
        <section class="form my-4 mx-5">
            <div class="container"> 
                <div class="row no-gutters">
                    <div class="col-lg-5">
                        <img src="../img/pets.jpg" class="img-fluid" alt="">
                    </div>
                    <div class="col-lg-7 px-5 pt-5">
                        <h1 class="font-weight-bold py-3"><img src="../img/logoprojeto.png" class="img-fluid" alt=""></h1>
                        <h4>Entre com sua conta</h4>
                        <form>
                            @Html.Partial("_Notifications")
                            <div class="form-row">
                                <div class="col-lg-7">
                                    @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control my-3 p-4", placeholder = "Login" } })
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-lg-7">
                                    @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control p-4", placeholder = "Senha", type = "password" } })
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-lg-7">
                                    <input type="submit" value="Entrar" class="btn1 mt-3 mb-1" />
                                </div>
                            </div>
                            <p>Ainda não é um herói?<a href='@Url.Action("Create", "Usuario")'> Cadastre-se!</a></p>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    }
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}