SejaHeroi/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SejaHeroi.Models.Animal;

namespace SejaHeroi.Controllers
{
  public class AnimalController : BaseController
  {
    // GET: Animal
    public override ActionResult Index()
    {
      List<AnimalViewModel> animaisUsuario = _SejaHeroiContextAnimalUtil.GetAnimaisUsuario(new Guid(Session["UsuarioID"].ToString()));
      ViewBag.Title = "Meus Animais";
      return View(animaisUsuario);
    }

    public ActionResult AnimaisDoacoes()
    {
      List<AnimalViewModel> animaisDoacao = _SejaHeroiContextAnimalUtil.AnimaisDoacoes();
      ViewBag.Title = "Animais para doação";
      return View("Index", animaisDoacao);
    }

    public ActionResult AnimaisDesaparecidos()
    {
      List<AnimalViewModel> animaisDesaparecidos = _SejaHeroiContextAnimalUtil.AnimaisDesaparecidos();
      ViewBag.Title = "Animais Desaparecidos";
      return View("Index", animaisDesaparecidos);
    }

    // GET: Animal/Details/5
    public ActionResult Details(Guid? id)
    {
      if (id == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Animal animal = _SejaHeroiContext.Animals.Find(id);
      if (animal == null)
      {
        return HttpNotFound();
      }
      return View(animal);
    }

    // GET: Animal/Create
    public ActionResult Create()
    {
      return View(new AnimalViewModel());
    }

    // POST: Animal/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to, for 
    // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create([Bind(Include = "AnimalID,TamanhoAnimal,RacaAnimal,Nome,Idade,Situacao,Resenha,ByteFoto,Imagem,StatusVacina")] AnimalViewModel animalVM)
    {
      ValidaImagemModel(animalVM.Imagem);
      Animal animal = new Animal();

      if (ModelState.IsValid)
      {
        if (animalVM.Imagem != null)
        {
          using (var binaryReader = new System.IO.BinaryReader(animalVM.Imagem.InputStream))
            animal.Foto = binaryReader.ReadBytes(animalVM.Imagem.ContentLength);
        }

        animal.AnimalID = Guid.NewGuid();
        animal.Nome = animalVM.Nome;
        animal.RacaAnimal = animalVM.RacaAnimal;
        animal.Situacao = animalVM.Situacao;
        animal.TamanhoAnimal = animalVM.TamanhoAnimal;
        animal.Resenha = animalVM.Resenha;
        animal.Idade = animalVM.Idade;
        animal.StatusVacina = animalVM.StatusVacina;

        if (animal.Situacao == Enums.Situacao.DonoProprio) animal.UsuarioID = new Guid(Session["UsuarioID"].ToString());

        _SejaHeroiContext.Animals.Add(animal);
        _SejaHeroiContext.SaveChanges();

        AddNotificacaoSucesso("Registro criado");
        return RedirectToAction("Index");
      }

      return View(animal);
    }

    // GET: Animal/Edit/5
    public ActionResult Edit(Guid? id)
    {
      if (id == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Animal animal = _SejaHeroiContext.Animals.Find(id);
      if (animal == null)
      {
        return HttpNotFound();
      }
      AnimalViewModel animalViewModel = new AnimalViewModel()
      {
        AnimalID = animal.AnimalID,
        Nome = animal.Nome,
        RacaAnimal = animal.RacaAnimal,
        Situacao = animal.Situacao,
        TamanhoAnimal = animal.TamanhoAnimal,
        Resenha = animal.Resenha,
        Idade = animal.Idade,
        ByteFoto = animal.Foto,
        UsuarioID = animal.UsuarioID,
        StatusVacina = animal.StatusVacina
      };
      return View(animalViewModel);
    }

    // POST: Animal/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to, for 
    // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit([Bind(Include = "AnimalID,TamanhoAnimal,RacaAnimal,Nome,Idade,Situacao,Resenha,ByteFoto,Imagem, UsuarioID,StatusVacina")] AnimalViewModel animalVM)
    {
      ValidaImagemModel(animalVM.Imagem);
      if (ModelState.IsValid)
      {
        Animal animal = new Animal
        {
          AnimalID = animalVM.AnimalID,
          Nome = animalVM.Nome,
          RacaAnimal = animalVM.RacaAnimal,
          Situacao = animalVM.Situacao,
          TamanhoAnimal = animalVM.TamanhoAnimal,
          Resenha = animalVM.Resenha,
          Idade = animalVM.Idade,
          Foto = animalVM.ByteFoto,
          StatusVacina = animalVM.StatusVacina
        };

        if (animalVM.UsuarioID != null)
          animal.UsuarioID = new Guid(animalVM.UsuarioID.ToString());

        if (animalVM.Imagem != null)
        {
          using (var binaryReader = new System.IO.BinaryReader(animalVM.Imagem.InputStream))
            animal.Foto = binaryReader.ReadBytes(animalVM.Imagem.ContentLength);
        }

        _SejaHeroiContext.Entry(animal).State = EntityState.Modified;
        _SejaHeroiContext.SaveChanges();

        AddNotificacaoSucesso("Registro editado");
        return RedirectToAction("Index");
      }
      return View(animalVM);
    }

    private void ValidaImagemModel(HttpPostedFileBase imagem)
    {
      var imageTypes = new string[]{
                    "image/gif",
                    "image/jpeg",
                    "image/pjpeg",
                    "image/png"
                    ,"image/x-icon"
                };
      if (imagem != null)
      {
        if (imagem.ContentLength > 0)
        {
          if (!imageTypes.Contains(imagem.ContentType))
            ModelState.AddModelError("ImageUpload", "Escolha uma iamgem GIF, JPG ou PNG.");
        }
      }
    }

    // GET: Animal/Delete/5
    public ActionResult Delete(Guid? id)
    {
      if (id == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Animal animal = _SejaHeroiContext.Animals.Find(id);
      if (animal == null)
      {
        return HttpNotFound();
      }
      return View(animal);
    }

    // POST: Animal/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteConfirmed(Guid id)
    {
      Animal animal = _SejaHeroiContext.Animals.Find(id);
      _SejaHeroiContext.Animals.Remove(animal);
      _SejaHeroiContext.SaveChanges();
      AddNotificacaoSucesso("Registro excluído");
      return RedirectToAction("Index");
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing)
      {
        _SejaHeroiContext.Dispose();
      }
      base.Dispose(disposing);
    }

    public ActionResult Adotar(Guid? id)
    {
      if (id == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Animal animal = _SejaHeroiContext.Animals.Find(id);
      animal.UsuarioID = new Guid(Session["UsuarioID"].ToString());
      animal.Situacao = Enums.Situacao.Adotado;

      _SejaHeroiContext.Entry(animal).State = EntityState.Modified;
      _SejaHeroiContext.SaveChanges();
      List<AnimalViewModel> animaisUsuario = _SejaHeroiContextAnimalUtil.GetAnimaisUsuario(new Guid(Session["UsuarioID"].ToString()));

      AddNotificacaoSucesso("Adoção realizada");
      return View("Index", animaisUsuario);
    }
  }
}

SejaHeroi/Controllers/EnderecoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SejaHeroi.Data;
using SejaHeroi.Models;

namespace SejaHeroi.Controllers
{
    public class EnderecoController : BaseController
    {
        // GET: Endereco
        public override ActionResult Index()
        {
            return View(_SejaHeroiContext.Enderecoes.ToList());
        }

        // GET: Endereco/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Endereco endereco = _SejaHeroiContext.Enderecoes.Find(id);
            if (endereco == null)
            {
                return HttpNotFound();
            }
            return View(endereco);
        }

        // GET: Endereco/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Endereco/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UsuarioID,Bairro,Rua,CEP,Numero,Telefone,Celular,complemento")] Endereco endereco)
        {
            if (ModelState.IsValid)
            {
                //endereco.UsuarioID = Guid.NewGuid();
                _SejaHeroiContext.Enderecoes.Add(endereco);
                _SejaHeroiContext.SaveChanges();
                AddNotificacaoSucesso("Endereço cadastrado");
                return RedirectToAction("Index");
            }

            return View(endereco);
        }

        // GET: Endereco/Edit/
        public ActionResult Edit()
        {
            var id = new Guid(Session["UsuarioID"].ToString());
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Endereco endereco = _SejaHeroiContext.Enderecoes.Find(id);
            if (endereco == null)
            {
                endereco = new Endereco(id);
            }
            return View(endereco);
        }

        // POST: Endereco/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UsuarioID,Bairro,Rua,CEP,Numero,Telefone,Celular,complemento")] Endereco endereco)
        {
            var id = new Guid(Session["UsuarioID"].ToString());

            Endereco enderecoEncontrado = _SejaHeroiContext.Enderecoes.Find(id);
            if (ModelState.IsValid)
            {
                if (enderecoEncontrado == null)
                {
                    _SejaHeroiContext.Enderecoes.Add(endereco);
                    _SejaHeroiContext.SaveChanges();
                    AddNotificacaoSucesso("Endereço cadastrado");
                    return RedirectToAction("Edit");
                }
                else
                {
                    _SejaHeroiContext.SaveChanges();
                    AddNotificacaoSucesso("Endereço atualizado");
                    return RedirectToAction("Edit");
                }
            }

            return View(endereco);
        }

        public ActionResult Delete()
        {
            var id = new Guid(Session["UsuarioID"].ToString());
            Endereco endereco = _SejaHeroiContext.Enderecoes.Find(id);
            if (endereco == null)
            { 
                    AddNotificacaoAviso("Não há endereço cadastrado!");
                    return RedirectToAction("Edit"); 
            } 
            _SejaHeroiContext.Enderecoes.Remove(endereco);
            _SejaHeroiContext.SaveChanges();
            AddNotificacaoSucesso("Endereço excluído");
            return RedirectToAction("Edit");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _SejaHeroiContext.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SejaHeroi/Controllers/UsuarioController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using SejaHeroi.Models;

namespace SejaHeroi.Controllers
{
    public class UsuarioController : BaseController
    {  
        // GET: Usuarios
        public override ActionResult Index()
        {
            
            return View(_SejaHeroiContext.Usuarios.ToList());
        }

        // GET: Usuarios/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = _SejaHeroiContext.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // GET: Usuarios/Create
        public ActionResult Create()
        {
            ViewBag.Perfil = TempData["Perfil"];
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UsuarioID,PerfilUsuario,Login,Senha,Email")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                usuario.UsuarioID = Guid.NewGuid();
                _SejaHeroiContext.Usuarios.Add(usuario);
                _SejaHeroiContext.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = _SejaHeroiContext.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UsuarioID,PerfilUsuario,Login,Senha,Email")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                _SejaHeroiContext.Entry(usuario).State = EntityState.Modified;
                _SejaHeroiContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = _SejaHeroiContext.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Usuario usuario = _SejaHeroiContext.Usuarios.Find(id);
            _SejaHeroiContext.Usuarios.Remove(usuario);
            _SejaHeroiContext.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _SejaHeroiContext.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SejaHeroi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/jquery-3.5.1.slim.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <link rel="stylesheet" href="~/styles/footer.css">

    <!-- Website CSS style -->
    <link rel="stylesheet" type="stylesheet" href="~/styles/template.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .navbar-inverse {
            background-color: #fff;
            border-color: #f2dede;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse-branca navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="~/Home/index">
                    <img src="~/img/logoprojeto.png" width="100" height="30" alt="" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Session["Perfil"].Equals(SejaHeroi.Enums.PerfilUsuario.Administrador))
                    {
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Controle de Usuários
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Usuários", "Index", "Usuario")</li>
                                <li>@Html.ActionLink("Criar Usuário", "Create", "Usuario")</li>
                            </ul>
                        </li>
                    }
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Castração<span class="caret"></span> </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Consultar Castrações", "Index", "FichaCastracao")</li>
                            <li>@Html.ActionLink("Agendar Castração", "Create", "FichaCastracao")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Animais <span class="caret"></span> </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastrar Animal", "Create", "Animal")</li>
                            <li>@Html.ActionLink("Meus Animais", "Index", "Animal")</li>
                            <li>@Html.ActionLink("Animais para doação", "AnimaisDoacoes", "Animal")</li>
                            <li>@Html.ActionLink("Animais Desaprecidos", "AnimaisDesaparecidos", "Animal")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Meu Endereço", "Edit", "Endereco")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <hr>
        @Html.Partial("_Notifications")
        @RenderBody()
        <hr />

        <footer class="footer-distributed">
            <hr>
            <div class="footer-left">
                <span><img src="~/img/logoprojeto.png" width="100" height="30" alt=""></span>
                <p class="footer-links">
                    <a href="#" class="link-1">Home</a>
                    <a href="#">Blog</a>
                    <a href="#">Cases</a>
                    <a href="#">Números</a>
                    <a href="#">Contribuir</a>
                    <a href="#">Sobre-nos</a>
                    <a href="#">Contato</a>
                </p>
                <p class="footer-company-name">Seja um herói © @DateTime.Now.Year Todos os direitos reservados</p>
            </div>

            <div class="footer-center">
                <div>
                    <i class="fa fa-envelope"></i>
                    <p><a href="mailto:support@company.com">contato@sejaumheroi.com.br</a></p>
                </div>
            </div>

            <div class="footer-right">

                <p class="footer-company-about">
                    <span>Sobre</span>
                    Seja um herói! Adote um pet e seja o herói dele. Ele vai ser seu fâ para sempre.<br />
                    Buscamos facilitar o trabalho dos heróis.
                </p>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SejaHeroi/Views/Shared/_Notifications.cshtml
@using SejaHeroi.Extensions

@{
    var errorList = Html.GetNotifications(NotificationType.ERROR);
    var warningList = Html.GetNotifications(NotificationType.WARNING);
    var successList = Html.GetNotifications(NotificationType.SUCCESS);
    var infoList = Html.GetNotifications(NotificationType.INFO);
}
<!-- display errors -->
@if (errorList != null)
{
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(errorList.Count() > 1){
            <strong><span class="glyphicon glyphicon-remove"></span> There are @errorList.Count() errors: </strong>
            <ul>
                @foreach (String message in errorList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-remove"></span>  </strong>
            @Html.Raw(errorList.First())
        }
    </div>
}

<!-- display warnings -->
@if (warningList != null)
{
    <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(warningList.Count() > 1){
            <strong><span class="glyphicon glyphicon-warning-sign"></span> There are @warningList.Count() warnings: </strong>
            <ul>
                @foreach (String message in warningList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-warning-sign"></span> </strong>
            @Html.Raw(warningList.First())
        }
    </div>
}

<!-- display success -->
@if (successList != null)
{
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(successList.Count() > 1){
            <strong><span class="glyphicon glyphicon-ok"></span> There are @successList.Count() successful notifications: </strong>
            <ul>
                @foreach (String message in successList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-ok"></span>  </strong>
            @Html.Raw(successList.First())
        }
    </div>
}

<!-- display success -->
@if (infoList != null)
{
    <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(infoList.Count() > 1){
            <strong><span class="glyphicon glyphicon-info-sign"></span> There are @infoList.Count() notifications: </strong>
            <ul>
                @foreach (String message in infoList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-info-sign"></span> </strong>
            @Html.Raw(infoList.First())
        }
    </div>
}